### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by RanjeetKumbhar01** [codeforcauseorg/ML-Bootcamp-July#2]
Code:
data = sns.load_dataset("tips")
sns.scatterplot(data["total_bill"], data["tip"], hue=data["smoker"])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [72], in <cell line: 1>()
----> 1 sns.scatterplot(data["total_bill"], data["tip"], hue=data["smoker"])

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

**Comment by kotturi-mahipal** [comment]
`sns.scatterplot(x='total_bill', y='tip', data=data, hue=data['smoker'])`
This will work. I think the syntax of seaborn is changed in the recent update. I too faced the same problem.

**Comment by RanjeetKumbhar01** [comment]
Yeah got it, Thanks!
